apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-logic-ui
  labels:
    app: json-logic-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: json-logic-ui
  template:
    metadata:
      labels:
        app: json-logic-ui
    spec:
      containers:
      - name: json-logic-ui
        image: json-logic-ui:latest  # Replace with your container registry image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: json-logic-ui-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 